<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME . " - Error"; ?></title>
        <!--<link rel="stylesheet" href="/assets/css/style.css">-->
    <style>
		body {
			height: 100vh;
			margin: 0;
			overflow: hidden;
			background-image: url("pattern.svg");
			background-repeat: repeat;
			background-color: rgb(52,52,52);
		}
		
		div#options.centered {
		display: flex;
		height: 100%;
		justify-content: center;
		align-items: center;
		}

		ul {
			list-style: none;
			text-align: center;
		}

		p {
			font-family: "Lato Hairline", Roboto, Arial;
			color: white;
			padding: 8px 5px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			font-size: 18px;
			margin: 4px 2px;
		}
		
		h1 {
			color: white;
			font-family: "Lato Black", Roboto, Arial;
			padding: 8px 10px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			font-size: 72px;
			margin: 4px 2px;
		}
		</style>
    </head>

	<body>
		<div id="options" class="centered">
			<ul>
			<li><h1>404</h1></li>
			<li><p>Media not found.</p></li>
			</ul> 
		</div>
	</body>
</html>